### PR TITLE
Added Kimi to namelist.txt

### PR DESCRIPTION
**Pull request by k-mie**

### CODE REVIEW

**Comment by fazreil** [comment]
Hi @k-mie

**Comment by k-mie** [comment]
> Hi @k-mie

hi @fazreil. asl?

**Comment by fazreil** [comment]
Saja je... Hew hew hew

**Comment by k-mie** [comment]
ni mesti bukan budak mIRC tak tau asl tu apa hahaha

**Comment by fazreil** [comment]
Igtkan hg cakap melayu

**Pull request merged**
